Install node and artillery

diff --git a/.github/workflows/loadtest.yml b/.github/workflows/loadtest.yml
--- a/.github/workflows/loadtest.yml
+++ b/.github/workflows/loadtest.yml
@@ -10,9 +10,33 @@ jobs:
   Artillery:
     runs-on: ubuntu-latest
 
+    strategy:
+      matrix:
+        node-version: [18.x, 20.x, 22.x]
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
+
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v4
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: "npm"
+
+      - run: npm ci
+      - run: npm run build --if-present
+      - run: npm test
+
+      - name: Install Artillery
+        run: npm install -g artillery
+
+      - name: Check if Artillery API Key is set
+        run: |
+          if [ -z "${{ secrets.ARTILLERY_API_KEY }}" ]; then
+            echo "Error: ARTILLERY_API_KEY is not set."
+            exit 1
+          fi
 
       - name: Backend Load Test
         run: |
